 FROM bellsoft/liberica-openjdk-alpine:11.0.16
 COPY ./java ./src
 RUN mkdir ./out
 RUN javac -sourcepath ./src -d out src/ru/vilonov/lesson1/sample/Main.java
 CMD java -classpath ./out ru.vilonov.lesson1.sample.Main